### ISSUE TITLE
[Tablehub Website] Issue tracking

### ISSUE THREAD

**Issue by devtronaut** [devtronaut/tablehub-website#11]
**Goal**
Users should be able to report bugs / issues / feedback for the Tablehub website.

**Acceptance**
- [ ] Implement Github issue and forms templates for the desired types of user feedback
- [ ] Link the issue page in the website to make it accessible from there
- [ ] Decision if the same process can be used for the reporting of issues with the tables

**Initial Thoughts / Idea Dump**
Have a minimal form to open issues directly from the tables, instead of only via the Tablehub website?
